services:
  - name: kekopoly
    type: web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGODB_URI
        sync: false # This will be set manually in Render.com dashboard
      - key: REDIS_URI
        sync: false # Set your Redis URI in Render.com dashboard
      - key: REDIS_PASSWORD
        sync: false # Set your Redis password in Render.com dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: DEV_SKIP_JWT
        value: "0"
      - key: PORT
        value: "8080"
      - key: VITE_API_URL
        value: "https://kekopoly.onrender.com"
    healthCheckPath: /health