export const boardSpaces = [
  // Corner spaces
  {
    id: 0,
    name: 'GO',
    type: 'corner',
    color: 'red.100',
  },
  {
    id: 10,
    name: 'Jail',
    type: 'corner',
    color: 'gray.100',
  },
  {
    id: 20,
    name: 'Free Parking',
    type: 'corner',
    color: 'green.100',
  },
  {
    id: 30,
    name: 'Go to Jail',
    type: 'corner',
    color: 'red.100',
  },

  // Properties
  {
    id: 1,
    name: 'Pepe Avenue',
    type: 'property',
    color: 'brown',
    price: 60,
    rent: 2,
    rents: [10, 30, 90, 160, 250],
    houseCost: 50,
    mortgageValue: 30,
  },
  {
    id: 3,
    name: 'Wojak Street',
    type: 'property',
    color: 'brown',
    price: 60,
    rent: 4,
    rents: [20, 60, 180, 320, 450],
    houseCost: 50,
    mortgageValue: 30,
  },
  {
    id: 6,
    name: 'Chad Boulevard',
    type: 'property',
    color: 'lightblue',
    price: 100,
    rent: 6,
    rents: [30, 90, 270, 400, 550],
    houseCost: 50,
    mortgageValue: 50,
  },
  {
    id: 8,
    name: 'Karen Lane',
    type: 'property',
    color: 'lightblue',
    price: 100,
    rent: 6,
    rents: [30, 90, 270, 400, 550],
    houseCost: 50,
    mortgageValue: 50,
  },
  {
    id: 9,
    name: 'Stacy Drive',
    type: 'property',
    color: 'lightblue',
    price: 120,
    rent: 8,
    rents: [40, 100, 300, 450, 600],
    houseCost: 50,
    mortgageValue: 60,
  },

  // Railroads
  {
    id: 5,
    name: 'Meme Express',
    type: 'railroad',
    price: 200,
    rent: 25,
    rents: [50, 100, 200],
    mortgageValue: 100,
  },
  {
    id: 15,
    name: 'Pepe Line',
    type: 'railroad',
    price: 200,
    rent: 25,
    rents: [50, 100, 200],
    mortgageValue: 100,
  },
  {
    id: 25,
    name: 'Wojak Rail',
    type: 'railroad',
    price: 200,
    rent: 25,
    rents: [50, 100, 200],
    mortgageValue: 100,
  },
  {
    id: 35,
    name: 'Chad Train',
    type: 'railroad',
    price: 200,
    rent: 25,
    rents: [50, 100, 200],
    mortgageValue: 100,
  },

  // Utilities
  {
    id: 12,
    name: 'Electric Company',
    type: 'utility',
    price: 150,
    rent: 4,
    mortgageValue: 75,
  },
  {
    id: 28,
    name: 'Water Works',
    type: 'utility',
    price: 150,
    rent: 4,
    mortgageValue: 75,
  },

  // Chance and Community Chest
  {
    id: 7,
    name: 'Chance',
    type: 'chance',
    color: 'orange.100',
  },
  {
    id: 22,
    name: 'Chance',
    type: 'chance',
    color: 'orange.100',
  },
  {
    id: 36,
    name: 'Chance',
    type: 'chance',
    color: 'orange.100',
  },
  {
    id: 2,
    name: 'Community Chest',
    type: 'community_chest',
    color: 'blue.100',
  },
  {
    id: 17,
    name: 'Community Chest',
    type: 'community_chest',
    color: 'blue.100',
  },
  {
    id: 33,
    name: 'Community Chest',
    type: 'community_chest',
    color: 'blue.100',
  },

  // Tax
  {
    id: 4,
    name: 'Income Tax',
    type: 'tax',
    amount: 200,
    color: 'red.100',
  },
  {
    id: 38,
    name: 'Luxury Tax',
    type: 'tax',
    amount: 100,
    color: 'red.100',
  },
];

export const propertyGroups = {
  brown: [1, 3],
  lightblue: [6, 8, 9],
  pink: [11, 13, 14],
  orange: [16, 18, 19],
  red: [21, 23, 24],
  yellow: [26, 27, 29],
  green: [31, 32, 34],
  darkblue: [37, 39],
}; 