package mongodb

import (
	"context"

	"github.com/kekopoly/backend/internal/models"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

// UserStore handles database operations for users
type UserStore struct {
	users *mongo.Collection
}

// NewUserStore creates a new UserStore
func NewUserStore(db *mongo.Database) *UserStore {
	return &UserStore{
		users: db.Collection("users"),
	}
}

// CreateUser inserts a new user into the database
func (s *UserStore) CreateUser(ctx context.Context, user *models.User) error {
	// Generate a new ObjectID if one doesn't exist
	if user.ID.IsZero() {
		user.ID = primitive.NewObjectID()
	}

	result, err := s.users.InsertOne(ctx, user)
	if err != nil {
		return err
	}

	// Update the user's ID with the inserted ID (if it was generated by MongoDB)
	if insertedID, ok := result.InsertedID.(primitive.ObjectID); ok {
		user.ID = insertedID
	}

	return nil
}

// GetUserByEmail finds a user by their email address
func (s *UserStore) GetUserByEmail(ctx context.Context, email string) (*models.User, error) {
	var user models.User
	err := s.users.FindOne(ctx, bson.M{"email": email}).Decode(&user)
	if err != nil {
		return nil, err
	}
	return &user, nil
}

// GetUserByUsername finds a user by their username
func (s *UserStore) GetUserByUsername(ctx context.Context, username string) (*models.User, error) {
	var user models.User
	err := s.users.FindOne(ctx, bson.M{"username": username}).Decode(&user)
	if err != nil {
		return nil, err
	}
	return &user, nil
}

// GetUserByID finds a user by their ID
func (s *UserStore) GetUserByID(ctx context.Context, id primitive.ObjectID) (*models.User, error) {
	var user models.User
	err := s.users.FindOne(ctx, bson.M{"_id": id}).Decode(&user)
	if err != nil {
		return nil, err
	}
	return &user, nil
}

// UpdateUser updates an existing user in the database
func (s *UserStore) UpdateUser(ctx context.Context, user *models.User) error {
	_, err := s.users.ReplaceOne(ctx, bson.M{"_id": user.ID}, user)
	return err
}
