version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: kekopoly-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=kekopoly
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/kekopoly --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: kekopoly-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build: .
    image: kekopoly-backend:latest
    container_name: kekopoly-server
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - REDIS_URI=redis:6379
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data: